
CREATE DATABASE burgers;

USE burgers;

CREATE TABLE burgers(
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(80) NOT NULL,
devoured BOOLEAN DEFAULT false,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);
